// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Hori Bunny":return img`
......................
......................
.............ddd......
..........ddd1d.1.....
..........dd.1..1.....
............1111......
...........111111.....
...........111f11f....
...........11111b.....
...........111111.....
.....dd.11111111d.....
.....dd.1111dddd......
.......d11111d........
.......d11111d........
.......d1dddddd.......
.......ddd....d.......
.........dddd.........
......................
......................
......................
......................
......................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
